repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: check-case-conflict
    - id: detect-private-key 
  - repo: https://github.com/crate-ci/typos
    rev: v1.0.11
    hooks:
      - id: typos
