sudo: false
language: rust

before_script:
  - cargo install cobalt-bin --features="syntax-highlight"
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cobalt build

after_success: |
  [ $TRAVIS_BRANCH = source ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cobalt import --branch master &&
  git config user.name "Travis CI Worker" &&
  git config user.email "eopage@byu.net" &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master

env:
   global:
      secure: "OEkdUu/+GsbYaZ8gC0TjztNl022B5bbSVlc1KltaFU5VnmfHW3YQ/jXmigSwfhZpOKLVHO3MxjgCCBhJfeDXpYsbJt282PMCtk1hBPh03eF02QzklxCTk7rlwXemkr9MKC6BYE1Snin3QY6XyiZyGhgGSohXCOnOH0YCdwOyVNVIbd5tLy6O6zoxyE4SLs8Yk9X8Vfk5j8eN6itZ4LSS3kcmFtE4dFo+S+DxK7HIRQKot0SM9g7OBB4lEnjqg1D78oksdpl310zoLeNHTgwRzcZ06nEYjgUvmDAicgba79wTOhu6QoTYoDZg6xEFoBNhJqMO3qxov6To59cv3SAUBQcsLqAYHTVgcjjBc4dsZeFXidJFTyckpalJHaTJNtsvfN28yeESB3Yu22Anan5n3socoIyWctoQwrCwwyZT9V1XFhVsoGhzSk/dMXUY9JHdIzBWhI9jRDFPPrS1LUbB6TYrV2C64RPHArKMvlKKshh7m42CeE2WktOxvZB8kaZ/bL9byJmnsMYphBKtoLA3F8OY4CY0T1ir58Fpl3xhAQPUHJIck7zwCx/HV2GToRzYmKK+tnY3b8FLS056+LycfSFRSfok3crCW8s8q+lMvrluLeXE3R191ePsLlrWkc24HqIRBickaDvz+e+mbgmkptHv7IJy6jjXF0hWxzdxWLA="
