sudo: false
before_script:
- curl -LSfs https://japaric.github.io/trust/install.sh | sh -s -- --git cobalt-org/cobalt.rs
  --crate cobalt --force --target x86_64-unknown-linux-gnu
- export PATH="$PATH:~/.cargo/bin"
script:
- cobalt build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GH_TOKEN"
  local_dir: build
  target_branch: master
  on:
    branch: source
env:
  global:
  - secure: bTnyH3lR0ae31bBpF7XZ8LE6TSw2nHvLALs4itp91gstQPSe9ouStr3bq2plDuZOp81YnztLZoFiOebUjsR5Y1X1DohdzOQm5LcInokzQ/qle3S5KIN/cKmpfIIDq+7YijrZk4qdTx0b9oibEsNyjcAcqBm4QDFrBanKl8y6Af6DFA1KWiRoWSQUoYomYU+aEHsdrFNKvOM2309c1F6Ut5GmOqg/mjUPhONk5V+iZWKCVKO5M03t6H8yK/OKHakumhGj8RKRIyLn/ewwHc7YLJP2NgpWS6+xNpodPXr84MvE8qivpXnljgsOUMXGalRwNmCagpdFubLlpXu9sfyv5YyYiehjTwBOG7h5oXh/squdYWGSQzqx5rVG+PH6CM/CgGvOAfxiUz7EmFolWu0Fi3AjQtcvNQvS2uNBslCMt6QxUebSZltSDHtLb7LiOHnK6PXYFexZuBVATDxyT4ZAlpfzrcAvknVzU/jQvU3nk7fG6n+lNF5F4iaQ//ru3XI2pwlm40pZYvgesoKLIoUZ4JQMpIaT0WUBE3IjPimuBDZuvLFnjXARgFNaA1JlW6nm07MlQQ/sGsybgRwx9n1GS6MfFCg7t8bLJPgZpe4sjnu0/ucI0vrs7HQ+D4MZrcDm1G2JSErj7j76wFgtpL9Yo0l4OKGrbgfD5AwlTyj9weg=
