sudo: false
language: rust

before_script:
  - cargo install cobalt-bin --features="syntax-highlight"
  - export PATH="$PATH:/home/travis/.cargo/bin"

cache: cargo
script:
  - cobalt build

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  cobalt import &&
  git config user.name "Travis CI Worker" &&
  git config user.email "eopage@byu.net" &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
